---
title: "Full Report"
output: html_document
---


# Background

New York City is infamous for the rodents that live among us. Our apartments, buildings, subway stations, trash cans, parks, and streets are home to millions of rats and other [rodents](https://www.nytimes.com/2021/11/05/nyregion/nyc-rats-sightings.html). For many New Yorkers, rodents are an inevitable part of everyday life, and one that has worsened in recent years. This year alone (2022), New York's Sanitation Department has reported more than 21,600 rat complaints. This represents a 71% increase since [October 2020](https://www.npr.org/2022/10/20/1130150756/new-york-rats-trash-rule-mayor-eric-adams). The issue has gotten so bad that Mayor Adams is now looking to hire a [“bloodthirsty” director](https://www.msn.com/en-ca/news/world/nyc-is-looking-for-bloodthirsty-rat-czar-and-the-job-pays-228-000/ar-AA14Qidf?li=AAggFp4) of rodent mitigation, who is eligible to make up to $228,000. Given the prevalence of rodents in this city and the recent urgency of the issue, this project primarily seeks to explore trends in rodent infestation across New York City.

Further, research shows that exposure to rodents is associated with a wide variety of diseases and poor health outcomes, including asthma symptoms. Asthma symptoms have been increasing in middle to high-income countries, making this issue ever more important. Understanding it can aid public health and health care combat diseases from these exposures. This is particularly an issue among communities that are historically and continually oppressed through racism and classism as they live in environments with higher levels of exposure due to air pollution, old buildings, cigarette smoke, and other factors. This project secondarily seeks to explore associations between rodent infestations and asthma prevalence in New York City.

# Questions

This project is motivated by the following questions: 

* What trends are there in rodent infestations throughout NYC? 
* How does it vary by neighborhood? How are rodent trends associated with asthma trends?
* What are potential confounders of the relationship between rodent infestations and asthma?
